apiVersion: apps/v1
kind: Deployment
metadata:
  name: carnode124-demo
  namespace: default
  labels:
     app: carnode124-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: carnode124-demo
  template:
    metadata:
      labels:
        app: carnode124-demo
    spec:
      containers:
      - name: nodeapp
        image: sreya1805/carnode124-demo
---
apiVersion: v1
kind: Service
metadata:
  name: carnode124-demo
  namespace: default
  labels:
     app: carnode124-demo
spec:
  type: NodePort
  selector:
     app: carnode124-demo
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30124



